gatling:
  baseUrl: http://localhost:8080
  intensity: ${intensity:-500} # maximal number of users on the last stage
  rampDuration: ${rampDuration:-10} # time (seconds) for ramp-up stage
  stageDuration: ${stageDuration:-60} # time (seconds) for load stage
  stages: ${stages:-5} # number of load stages

nfr:
  maxResponseTime: ${maxResponseTime:-500} # simulation is considered failed if max response time is greater
  perc95ResponseTime: ${perc95ResponseTime:-100} # simulation is considered failed if p95 response time is greater
  failedRequests: ${failedRequests:-1} # simulation is considered failed if failed requests percent is greater
