# This is a basic workflow to help you get started with Actions

name: Performance Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  max_performance_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Start Docker image
      run: |
        docker load -i ./app/todo-app.tar
        docker run -d -p 8080:4242 --name todo-app todo-app:latest

    - name: Compile tests
      run: ./gradlew clean build

    - name: Run MaxPerformance simulation
      run: ./gradlew gatlingRun --simulation todo.simulations.MaxPerformance

    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: max-perf-report
        path: build/reports/gatling
        retention-days: 7
        overwrite: true
